<?php

namespace App\Services;

use function PHPSTORM_META\map;

class FormularioSocioeconomico {


  // IDENTIFICACIÓN DEL ALUMNO/A Y GRUPO FAMILIAR
  const FORMULARIO_GENERAL = [
    10 => ['FORMULARIO DE POSTULACIÓN A BENEFICIOS (FUAS) <strong>DOCUMENTOS OBLIGATORIO</strong>'],
    20 => ['CARTOLA REGISTRO SOCIAL DE HOGARES'],
    30 => ['FOTOCOPIA CÉDULA DE IDENTIDAD POR AMBOS LADOS O CERTIFICADO DE NACIMIENTO PARA ASIGNACIÓN FAMILIAR (ALUMNO Y TODOS LOS INTEGRANTES DEL GRUPO FAMILIAR). <strong>DOCUMENTO OBLIGATORIO</strong>'],
    40 => ['CERTIFICADO ALUMNO REGULAR DE LOS INTEGRANTES DEL GRUPO FAMILIAR QUE SE ENCUENTREN ESTUDIANDO EN ENSEÑANZA BÁSICA, MEDIA O SUPERIOR. <strong>DOCUMENTO OBLIGATORIO SEGÚN CORRESPONDA</strong>'],
    50 => ['CERTIFICADO DE RESIDENCIA DEL ALUMNO EMITIDA POR JUNTA DE VECINOS O FORMATO MINEDUC (ADJUNTAR UNA CUENTA DE SERVICIOS BÁSICOS). <strong>DOCUMENTO OBLIGATORIO</strong>'],
    60 => ['CERTIFICADO DE DEFUNCIÓN (EN CASO DE FALLECIMIENTO DE UNO DE LOS PADRES O INTEGRANTE INCORPORADO EN FUAS). <strong>DOCUMENTO OBLIGATORIO SEGÚN CORRESPONDA</strong>'],
    70 => ['CERTIFICADO DE EGRESO CARRERA TÉCNICA (POSTULANTES ARTICULACIÓN DE ESTUDIOS). <strong>DOCUMENTO OBLIGATORIO SEGÚN CORRESPONDA</strong>'],
    80 => ['CONCENTRACIÓN DE NOTAS DE ENSEÑANZA MEDIA. <strong>DOCUMENTO OBLIGATORIO</strong>'],
  ];

  // INGRESOS DEL GRUPO FAMILIAR: El ALUMND DEBERA PRESENTAR LOS SIGUIENTES DOCUMENTOS SEGÚN EL TIPO DE INGRESO DEL GRUPO FAMILIAR (A, B, C, D Ó E)


  // A) DOCUMENTOS OBLIGATORIOS PARA TODDS LOS INTEGRANTES MAYORES A 18 AÑOS (TENGAN O NO MOVIMIENTO)
  const FORMULARIO_A = [
    10 => ['CONSULTA DE AFILIACIÓN DE AFP DESDE LA PÁGINA DE LA SUPERINTENDENCIA DE PENSIONES'],
    20 => ['CERTIFICADO DE COTIZACIONES PREVISIONALES CON REMUNERACION IMPONIBLE AÑO 2022 (AFP). <strong>NO SE ACEPTAN CERTIFICADOS PREVIRED</strong>'],
    30 => ['CONSULTA TRIBUTARIA A TERCEROS DESDE LA PAGINA DEL SII.'],
  ];

  // B) TRABAJADORES DEPENDIENTES

  const FORMULARIO_B = [
    10 => ['6 ÚLTIMAS LIQUIDACIONES DE SUELDO O CERTIFICADO DE RENTA EMITIDO POR EMPLEADOR, <strong>(MÍNIMO 3 ÚLTIMAS LIQUIDACIONES)</strong>'],
    20 => ['12 ÚLTIMAS LIQUIDACIONES PARA INTEGRANTES DEL GRUPO FAMILIAR PERTENECIENTESA CARABINEROS, PDI O GENDARMERÍA <strong>(DOCUMENTO OBLIGATORIO)</strong>'],
    30 => ['CERTIFICADO DE RENTA CON REMUNERACIONES AÑO 2022 PARA INTEGRANTES DEL GRUPO FAMILIAR PERTENECIENTES A FUERZAS ARMADAS <strong>(DOCUMENTO OBLIGATORIO)</strong>'],
  ];


  // C) TRABAJADORES INDEPENDIENTES

  const FORMULARIO_C = [
    10 => ['RESUMEN ANUAL DE BOLETAS DE HONORARIOS PERIODO 2022'],
    20 => ['CERTIFICADO DE COTIZACIONES PREVISIONALES (AFP) AÑO 2022'],
    30 => ['FORMULARIO 29 (IVA) CORRESPONDIENTE AL PERIODO 2022 <strong>(CARPETA TRIBUTARIA PARA CRÉDITO)</strong>'],
    40 => ['FORMULARIO 22 SOLEMNE Y COMPACTO DECLARACIÓN DE RENTA PERIODO 2022 <strong>(CARPETA TRIBUTARIA PARA CRÉDITO)</strong>'],
  ];


  // D) PENSIONADO

  const FORMULARIO_D = [
    10 => ['ÚLTIMO COMPROBANTE DE PAGO DE PENSIÓN (VEJEZ, INVALIDEZ, SOBREVIVENCIA)· MESES OCTUBRE O NOVIEMBRE 2022'],
  ];

  // E) OTROS INGRESOS

  const FORMULARIO_E = [
    10 => ['PENSIÓN ALIMENTICIA CON RESPALDO JUDICIAL, (ADJUNTAR RESOLUCIÓN JUDICIAL, ACUERDO EXTRA JUDICIAL, O LIBRETA DE BANCO DONDE SE DEPOSITA MONTO PACTADO)'],
    20 => ['PENSION ALIMENTICIA SIN RESPALDO JUDICIAL, <strong>EN EL CASO DE NO SER El ÚNICO INGRESO DEL GRUPO FAMILIAR</strong> (ADJUNTAR CERTIFICADO PENSIÓN DE ALIMENTOS FORMATO MINEDUC, ÚLTIMA LIQUIDACIÓN DE SUELDO DE QUIEN ENTREGUE LA PENSIÓN Y CERTIFICADO DE RESIDENCIA DE AMBOS PADRES)'],
    30 => ['PENSION ALIMENTICIA SIN RESPALDO JUDICIAL, <strong>EN EL CASO DE SER EL ÚNICO INGRESO DEL GRUPO FAMILIAR</strong> (ADJUNTAR CERTIFICADO DE PENSIÓN DE ALIMENTOS FORMATO MINEDUC EL QUE DEBE SER ACOMPAÑADO DE LOS SIGUIENTES DOCUMENTOS: ÚLTIMA LIQUIDACIÓN DE SUELDO, FOTOCOPIA DE CÉLULA DE IDENTIDAD DE QUIEN ENTREGA LA PENSIÓN, CERTIFICADO DE RESIDENCIA DE AMBOS PADRES, FOTOCOPIA DE CUENTA A NOMBRE DE QUIEN ENTREGUE LA PENSIÓN) 0 INFORME SOCIAL. QUE DETALLE SITUACIÓN FAMILIAR EMITIDO POR TRABAJADOR(A) SOCIAL CON DEPENDENCIA EN ALGUNA DE LAS SIGUIENTES INSTITUCIONES: MUNICIPALIDADES, CONSULTORIOS, GOBERNACIÓN, INTENDENCIA, ESTABLECIMIENTO EDUCACIONAL DE EGRESO DEL POSTULANTE. (DOCUMENTO TIMBRADO Y FIRMADO POR PROFESIONAL E INSTITUCIÓN)'],
    40 => ['APORTE DE TERCEROS (CERTIFICADO DE APORTE DE TERCEROS O PARIENTES Y FOTOCOPIA DE CÉLULA DE IDENTIDAD DE QUIEN ENTREGA APORTE) <strong>APORTE QUE REALICEN LOS PADRES DEL POSTULANTE NO SON SERAN VALIDOS EN ESTA SECCIÓN</strong>'],
    50 => ['INFORME SOCIAL O FICHA SOCIOECONOMICA FORMATO MINEDUC PARA TRABAJADORES INFORMALES (JARDINEROS, ARTESAÑOS, VENDEDORES AMBULANTES, VENDEDOR EN FERIAS LIBRES, ETC) + DECLARACIÓN DE GASTOS MENSUALES Y 3 BOLETAS DE CONSUMO BÁSICO'],
    60 => ['INGRESOS POR ARRIENDO DE BIENES INMUEBLES, COPIA DEL CONTRATO DE ARRENDAMIENTO Y ÚLTIMO PAGO DE ARRIENDO'],
    70 => ['RETIROS, DIVIDENDOS POR ACCIONES, INTERESES MOBILIARIOS Y GANANCIAS DE CAPITAL (FORM. 22 Y CONSTITUClÓN DE LA SOCIEDAD) (CARPETA TRIBUTARIA PARA CRÉDJTO)'],
    80 => ['DOCUMENTO DE AFC O EMPLEADOR EN CASO DE ESTAR O HABER ESTADO ACOGIDO A LA LEY DE PROTECCÓN DEL EMPLEO <strong>(DOCUMENTO OBLIGATORIO SEGÚN CORRESPONDA)</strong>'],
    90 => ['FINIQUITO PERIODO 2021 EN CASO DE CESANTÍA DE ALGÚN INTEGRANTE DEL GRUPO FAMILIAR'],
    100 => ['CARPETA TRIBUTARIA A TODOS LOS INTEGRANTES QUE CUENTEN CON INGRESOS FORMALES IGUAL O SUPERIORA $800.000 <strong>(OBLIGATORIA)</strong>'],
  ];

//   "'  NO SE ACEPTAAANINFORMES SOOALES O FlCHAS SOOOECONOMICASCON INGRESOS ENMONTO $0 O DOCUMENTOSSINTIMBRE INSTJTUOONALDERESPALDO
// OEOLARO QUELOS DOC\JMENTOSENTREGADOSSON VERfDICOS, ASf COMO ESTAR EN CONOCIMIENTO QUE EN El CASO DEOMITJR ANTECEDENTESDE Ml SITUACION SOCIOECON0MICA, LA INSTJTUOONPODRA SOLIOTAR DOCUMENTOS ADICIONALES."



  public function call() {
    return [
      'GENERAL' => [
        'title' => 'IDENTIFICACIÓN DEL ALUMNO/A Y GRUPO FAMILIAR',
        'class' => '',
        'values' => SELF::FORMULARIO_GENERAL,
      ],
      'A' => [
        'title' => 'A) DOCUMENTOS OBLIGATORIOS PARA TODDS LOS INTEGRANTES MAYORES A 18 AÑOS (TENGAN O NO MOVIMIENTO)',
        'class' => '',
        'values' => SELF::FORMULARIO_A,
      ],
      'B' => [
        'title' => 'B) TRABAJADORES DEPENDIENTES',
        'class' => '',
        'values' => SELF::FORMULARIO_B,
      ],
      'C' => [
        'title' => 'C) TRABAJADORES INDEPENDIENTES',
        'class' => '',
        'values' => SELF::FORMULARIO_C,
      ],
      'D' => [
        'title' => 'D) PENSIONADO',
        'class' => '',
        'values' => SELF::FORMULARIO_D,
      ],
      'E' => [
        'title' => 'E) OTROS INGRESOS',
        'class' => '',
        'values' => SELF::FORMULARIO_E,
      ],
    ];
  }
}
